### ISSUE TITLE
Error: No module named 'dateutil'

### ISSUE THREAD

**Issue by chrisgrieser** [ariestwn/alfred-natural-calendar#1]
After setting up via `clprofile`, I try to run `cl` and then get this error in Alfred's debugging log:

```
[11:05:34.193] ERROR: NLP Calendar[Script Filter] Code 1: Traceback (most recent call last):
  File "/Users/chrisgrieser/.config/Alfred.alfredpreferences/workflows/user.workflow.9A586113-094B-4D2D-B32C-16CE94694481/./preview.py", line 8, in <module>
    from dateutil import parser
ModuleNotFoundError: No module named 'dateutil'
```

**Comment by ariestwn** [comment]
> After setting up via `clprofile`, I try to run `cl` and then get this error in Alfred's debugging log:
> 
> ```
> [11:05:34.193] ERROR: NLP Calendar[Script Filter] Code 1: Traceback (most recent call last):
>   File "/Users/chrisgrieser/.config/Alfred.alfredpreferences/workflows/user.workflow.9A586113-094B-4D2D-B32C-16CE94694481/./preview.py", line 8, in <module>
>     from dateutil import parser
> ModuleNotFoundError: No module named 'dateutil'
> ```

This can be solved by installing python-dateutil.

**Comment by chrisgrieser** [comment]
Well, it isn't documented anywhere that you need to install an extra dependency, so no user will be able to know. 

Nonetheless, it might be useful to simply include it the workflow to keep things simple for the user?

**Comment by ariestwn** [comment]
> Well, it isn't documented anywhere that you need to install an extra dependency, so no user will be able to know.
> 
> Nonetheless, it might be useful to simply include it the workflow to keep things simple for the user?

Thanks. I will add it to the requirements section and the info.plist.

**Comment by chrisgrieser** [comment]
I would really recommend shipping the package with the workflow rather than just adding it to the readme, since the average user does not know how to install Python packages.

**Comment by ariestwn** [comment]
> I would really recommend shipping the package with the workflow rather than just adding it to the readme, since the average user does not know how to install Python packages.

Hi, please kindly check the new workflow update.
