### ISSUE TITLE
Do not store `calendar_profile.log` in workflow folder

### ISSUE THREAD

**Issue by chrisgrieser** [ariestwn/alfred-natural-calendar#2]
Right now, the log `calendar_profile.log` is stored in the workflow folder. Log data should not be stored in the workflow folder itself, but rather in`alfred_workflow_cache` or `alfred_workflow_data` ([accessible as environment variables from inside Alfred](https://www.alfredapp.com/help/workflows/script-environment-variables/)).

Also, the current release contains a `calendar_profile.log` from when you used the workflow. It contains a bunch of information that looks like your personal calendar usage, and some of the data look as if they were potentially private, so I'd even consider deleting the 1.0.0 release if those logs contain private data of yours?

**Comment by ariestwn** [comment]
Wow, thanks for the feedback! It's like I missed something in the package creation script.

**Comment by chrisgrieser** [comment]
Simply moving those should be fine. 

Though putting config data into the data folder is tricky, since it then went sync if the user syncs their config. I think simply selecting a default calendar via Alfred config might make most sense?
