### ISSUE TITLE
Keyword does not trigger workflow

### ISSUE THREAD

**Issue by brakai295** [ariestwn/alfred-natural-calendar#3]
Thanks for making this! I just installed it, but when I use the keyword, it just triggers a web search. 

I first see this:

<img width="647" alt="image" src="https://github.com/user-attachments/assets/17eae3d1-bd9e-41fc-bb02-a0d774895fee">

As I enter text it jumps back to the default search. (This happens also if I press Enter first.)

<img width="637" alt="image" src="https://github.com/user-attachments/assets/51e10feb-8074-44bf-bd63-70cf06d551fd">

**Comment by ariestwn** [comment]
This issue happened due to python dependency, please reinstall using the [updated workflow. ](https://github.com/ariestwn/alfred-natural-calendar/releases/tag/v1.0.1)
