### ISSUE TITLE
'clprofile' success yet still adds to default icloud 'Home' calendar (also lack of clarity for using '#' to add to calendars with spaces)

### ISSUE THREAD

**Issue by conformist1** [ariestwn/alfred-natural-calendar#6]
Hi there!

First off, thank you SO MUCH for this amazing offer.

Here's a screenshot showing the correct calendar as default:
![Screenshot 2024-11-10 at 2 28 41 PM](https://github.com/user-attachments/assets/2feeb841-c8df-43ab-a1ef-a437ae6a7fa7)

After adding an event, it successfully adds but does so in iCloud's 'Home' calendar. Let me know if there's anything else needed for debugging. 

Also, I'd like to be able to add to a secondary calendar with an ampersand and spaces in the name. How would I go about doing this? It seems the '#' only allows for contiguous text and doesn't support quotes etc.

Thanks!

**Comment by ariestwn** [comment]
Hi, thanks for the feedback, yeah I notice and there is a problem with calendar selection both in calendar_profile.py and calendar_nlp.py.

I also updated the script to be able to parse the Calendar profile with spaces in the name. But it still only works for one profile calendar.
<img width="615" alt="image" src="https://github.com/user-attachments/assets/3f2a772c-fc9e-42d0-810d-bba4868b0f81">

please check the new update [here](https://github.com/ariestwn/alfred-natural-calendar/releases/tag/v1.0.4)
